LANGUAGE = tlingit
EAF = 15LillianAnita231220SlexilAT.eaf
HTML.FILE = 15LillianAnita.html
TIER.GUIDE = tierGuide.yaml
SFMT.FILE = 15LillianAnita231220SlexilAT.yaml
VID = 15LillianAnita.m4v
TITLE = "Tlingit Conversation \#15"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
