EAF = 81AlHarold230721Slexil.eaf
SFMT.FILE = 81AlHarold230721Slexil.yaml
HTML.FILE = 81AlHarold.html
VID = 81AlHarold.mov
TITLE = "Tlingit Conversation \#81"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
