LANGUAGE = tlingit
#EAF = 6ArchieGeorge230714Slexil.eaf
EAF = archieGeorgeOffline.eaf
HTML.FILE = 6ArchieGeorge.html
SFMT.FILE = archieGeorgeOffline.yaml
TIER.GUIDE = tierGuide.yaml
VID = ArchieGeorge6.mov
TITLE = "Tlingit Conversation \#6"

include ../makefile-shared
