
include ../../makefile-shared
LANGUAGE = degXinag
BASE = Earthquake241024
EAF =  $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HELP_FILE = help.html
HTML.FILE = earthquake.html
VID = EarthquakeDX2.wav
TITLE = "Ngan’ Dit’anh Earthquake"
HOST = https://aklanguages.uas.alaska.edu

