LANGUAGE = tlingit
EAF = 3SmithJoe230627Slexil.eaf
# EAF = 3SmithJoe250729Slexil.eaf
HTML.FILE = 3SmithJoe.html
SFMT.FILE = 3SmithJoe230627Slexil.yaml
VID = 3SmithJoeVOLume.m4v
TITLE = "Tlingit Conversation \#3"

include ../makefile-shared
# HELP_FILE = help.html
