LANGUAGE = tlingit
EAF = 40TeslinLadies231011Slexil.eaf
SFMT.FILE = 40TeslinLadies231011Slexil.yaml
HTML.FILE = 40TeslinLadies.html
VID = 40TeslinLadies.m4v
TITLE = "Tlingit Conversation \#40"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
