LANGUAGE = tlingit
EAF = 25NellieLena230714Slexil.eaf
SFMT.FILE = 25NellieLena230714Slexil.yaml
HTML.FILE = 25NellieLena.html
VID = LenaNellie25.mov
TITLE = "Tlingit Conversation \#25"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
