LANGUAGE = tlingit
EAF = 11DavidGeorge230503Slexil.eaf
SFMT.FILE = 11DavidGeorge230503Slexil.yaml
HTML.FILE = 11DavidGeorge.html

VID = 11DavidGeorge.mov
TITLE = "Tlingit Conversation \#11"

include ../makefile-shared
