EAF = 68AdelineGenevieve230703Slexil.eaf
SFMT.FILE = 68AdelineGenevieve230703Slexil.yaml
HTML.FILE = 68AdelineGenevieve.html
VID=68AdelineGenevieve.m4v
TITLE = "Tlingit Conversation \#68"

include ../makefile-shared
