EAF = 76SelinaMargaret230714Slexil.eaf
SFMT.FILE = 76SelinaMargaret230714Slexil.yaml
HTML.FILE = 76SelinaMargaret.html
VID=76SelinaMargaretAll.mov
TITLE = "Tlingit Conversation \#76"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
