EAF = 4EthelAnita230503Slexil.eaf

default:
	@echo venv
	@echo run

venv:
	@echo source /Users/paul/github/slexil2/py3105slexil/bin/activate

run:
	python ../../utils/eaf2html.py  \
      --eaf $(EAF) \
      --tierGuide tierGuide.yaml \
      --pageTitle slow 

