EAF = 74AdelineLarry230711Slexil.eaf
SFMT.FILE = 74AdelineLarry230711Slexil.yaml
HTML.FILE = 74AdelineLarry.html
VID=74AdelineLarry.m4v
TITLE = "Tlingit Conversation \#74"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
