EAF = 96LizVernaSelina230805Slexil.eaf
SFMT.FILE = 96LizVernaSelina230805Slexil.yaml
HTML.FILE = 96VernaLizSelina.html
VID = 96VernaLizSelinaEdit.mp4
TITLE = "Tlingit Conversation \#96"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
