LANGUAGE = tlingit
EAF = 17Cook240109Slexil.eaf
HTML.FILE = 17Cook.html
SFMT.FILE = 17Cook240109Slexil.yaml
TIER.GUIDE = tierGuide.yaml
VID = CookIt.m4v
TITLE = "Tlingit Conversation \#17"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
