EAF = 86GeorgeMargaret230724Slexil.eaf
SFMT.FILE = 86GeorgeMargaret230724Slexil.yaml
HTML.FILE = 86GeorgeMargaret.html
VID = 86GeorgeMargaret.m4v
TITLE = "Tlingit Conversation \#86"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
