LANGUAGE = tlingit
EAF = 18Dance230713Slexil.eaf
HTML.FILE = 18Dance.html
SFMT.FILE = 18Dance230713Slexil.yaml
TIER.GUIDE = tierGuide.yaml
VID = dance.mp4
TITLE = "Tlingit Conversation \#18"

include ../makefile-shared
