LANGUAGE = tlingit
EAF = 46Carcross240808Slexil.eaf
SFMT.FILE = 46Carcross240808Slexil.yaml
HTML.FILE = 46Carcross.html
VID = 46Carcross.m4v
TITLE = "Tlingit Conversation \#46"

include ../makefile-shared
