EAF = 66GeorgePaul230630Slexil.eaf
SFMT.FILE = 66GeorgePaul230630Slexil.yaml
HTML.FILE = 66GeorgePaul.html
VID=66GeorgePaul.m4v
TITLE = "Tlingit Conversation \#66"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
