LANGUAGE = tlingit
EAF = 2EvelynMarsh230503Slexil.eaf
HTML.FILE = 2EvelynMarsha2.html
SFMT.FILE = 2EvelynMarsh230503Slexil.yaml
VID = 2EvelynMarsha.mp4
TITLE = "Tlingit Conversation \#2"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
