include ../../makefile-shared
LANGUAGE = degXinag
BASE = GrowingUp241111
EAF = $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HTML.FILE = nasiyonhGrowingUp.html
VID = growing-up.wav
TITLE = "Nasiyonh Growing Up"
HELP_FILE = "../../help-tlingit.html"
HOST = https://aklanguages.uas.alaska.edu
