EAF = 71DaltonDutson230705Slexil.eaf
SFMT.FILE = 71DaltonDutson230705Slexil.yaml
HTML.FILE = 71DaltonDutson.html
VID=71DaltonDutson.m4v
TITLE = "Tlingit Conversation \#71"

include ../makefile-shared
