LANGUAGE = tlingit
EAF = 22CyrilG230307AT.eaf
VID = 22CyrilG.mov
HTML.FILE = 22CyrilG.html
SFMT.FILE = 22CyrilG230307AT.yaml
# SFMT.FILE = tmp.yaml
TITLE = "Tlingit Conversation \#22"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
