include ../../makefile-shared
LANGUAGE = degXinag
BASE = FirstAirplaneSee241031
EAF =  $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HELP_FILE = help.html
HTML.FILE = firstAirplaneSee.html
VID = DXCultHist7_3.wav
TITLE = "Xintthe q’unt’ux xiy naghitl’an xiy"
HOST = https://aklanguages.uas.alaska.edu

