LANGUAGE = tlingit
EAF = 56RuthMarsha230607Slexil.eaf
SFMT.FILE = 56RuthMarsha230607Slexil.yaml
HTML.FILE = 56RuthMarsha.html
VID = 56RuthMarsha.m4v
TITLE = "Tlingit Conversation \#56"

include ../makefile-shared
