EAF = 32RamosChester230528Slexil.eaf
SFMT.FILE = 32RamosChester230528Slexil.yaml
HTML.FILE = 32RamosChester.html
VID=32RamosChester.m4v
TITLE = "Tlingit Conversation \#32"

include ../makefile-shared
