# -*- tab-width: 3 -*-
# -*- coding: utf-8 -*-
#-------------------------------------------------------------------------------
import os, sys
import pdb
#-------------------------------------------------------------------------------
class MorphemeGlossAbbreviations:

   x = list()

   #----------------------------------------------------------------------
   def __init__(self):

     self.beckAndHess = {"1PO": "1st person possessive",
                         "2PO": "2nd person possessive",
                         "3PO": "third person possessive",
                         "3SUB": "third person subject",
                         "ADD": "additive",
                         "ADNM": "adjunctive nominalizer",
                         "ALTV": "allative applicative",
                         "ASSC": "associative",
                         "ATTN": "attenuative",
                         "AUTO": "autonomous",
                         "CLS": "classifier",
                         "CNN": "connective",
                         "CNTRPT": "centripetal",
                         "COORD": "coordinative",
                         "CTD": "contained",
                         "DAT": "dative applicative",
                         "DC": "diminished control",
                         "DIM.EFF": "diminished effectiveness",
                         "DIST": "distal",
                         "DMA": "demonstrative adverbial",
                         "DSD":  "desiderative",
                         "DSTR": "distributive",
                         "ECS": "external causative",
                         "FEM": "feminine",
                         "FOC": "focus",
                         "HAB": "habitual",
                         "HMN": "human",
                         "ICS": "internal causative",
                         "IMPF": "imperfective",
                         "INCH": "inchoative",
                         "INCRP": "incorporative",
                         "INT": "interrogative",
                         "INTJ": "interjection",
                         "INTNS": "intensivity",
                         "IRR": "irrealis",
                         "MAP": "middle applicative",
                         "MD": "middle",
                         "NEG": "negative",
                         "NEGP": "negative proclitic",
                         "NM": "nominalizer",
                         "NSPEC": "non-specific",
                         "OBJ": "object",
                         "PASS": "passive",
                         "PFV": "perfective",
                         "PL": "plural",
                         "PO": "possessive",
                         "PR": "preposition",
                         "PROC": "proclititive",
                         "PROG": "progressive",
                         "PROP": "propriative",
                         "PROX": "proximal",
                         "PRTV": "partitive",
                         "PTCL": "particle",
                         "QTV": "quotative",
                         "RCP": "reciprocal",
                         "REFL": "reflexive",
                         "REM": "remote/hypothetical",
                         "RLNL": "relational",
                         "SBJ": "subjunctive",
                         "SBRD": "subordinate",
                         "1SBRD": "subordinate",
                         "2SBRD": "subordinate",
                         "3SBRD": "subordinate",
                         "SCONJ": "sentential conjunction",
                         "SG":  "singular",
                         "SPEC": "specific",
                         "SS": "secondary suffix",
                         "STAT": "stative",
                         "SUB": "subject",
                         "UNQ": "unique"}

     self.leipzig = {"1": "first person",
                     "2": "second person",
                     "3": "third person",
                     "A": "agent-like argument of canonical transitive verb ABL ablative",
                     "ABS": "absolutive",
                     "ACC": "accusative",
                     "ADJ": "adjective",
                     "ADV": "adverb(ial)",
                     "AGR": "agreement",
                     "ALL": "allative",
                     "ANTIP": "antipassive",
                     "APPL": "applicative",
                     "ART": "article",
                     "AUX": "auxiliary",
                     "BEN": "benefactive",
                     "CAUS": "causative",
                     "CLF": "classifier",
                     "COM": "comitative",
                     "COMP": "complementizer",
                     "COMPL": "completive",
                     "COND": "conditional",
                     "COP": "copula",
                     "CVB": "converb",
                     "DAT": "dative",
                     "DECL": "declarative",
                     "DEF": "definite",
                     "DEM": "demonstrative DET determiner DIST distal",
                     "DISTR": "distributive",
                     "DU": "dual",
                     "DUR": "durative",
                     "ERG": "ergative",
                     "EXCL": "exclusive",
                     "F": "feminine",
                     "FOC": "focus",
                     "FUT": "future",
                     "GEN": "genitive",
                     "IMP": "imperative INCL inclusive",
                     "IND": "indicative INDF indefinite INF infinitive",
                     "INS": "instrumental INTR intransitive IPFV imperfective IRR irrealis",
                     "LOC": "locative",
                     "M": "masculine",
                     "N": "neuter",
                     "NEG": "negation, negative",
                     "NMLZ": "nominalizer/nominalization",
                     "NOM": "nominative",
                     "OBJ": "object",
                     "OBL": "oblique",
                     "P": "patient-like argument of canonical transitive verb PASS passive",
                     "PFV": "perfective",
                     "PL": "plural",
                     "POSS": "possessive",
                     "PRED": "predicative",
                     "PRF": "perfect",
                     "PRS": "present",
                     "PROG": "progressive",
                     "PROH": "prohibitive",
                     "PROX": "proximal/proximate",
                     "PST": "past",
                     "PTCP": "participle",
                     "PURP": "purposive",
                     "Q": "question particle/marker QUOT quotative",
                     "RECP": "reciprocal",
                     "REFL": "reflexive",
                     "REL": "relative",
                     "RES": "resultative",
                     "S": "single argument of canonical intransitive verb SBJ subject",
                     "SBJV": "subjunctive",
                     "SG": "singular",
                     "TOP": "topic",
                     "TR": "transitive",
                     "VOC": "vocative"}

     self.wikipedia = ["1SG", "2SG", "3SG", "1PL", "2PL", "3PL", 
        "0", "A", "AB", "ABE", "ABESS", "ABIL",
        "ABL", "ABLA", "ABM", "ABS", "ABSL", "ABSN", "ABSOL", "ABST",
        "ABSTR", "ABSV", "ABT", "AC", "ACAUS", "ACC", "ACCMP",
        "ACCOM", "ACH", "ACNNR", "ACNR", "ACP", "ACR", "ACT", "ACTL",
        "ACTY", "AD", "ADAP", "ADD", "ADDIR", "ADDIT", "ADE", "ADEL",
        "ADES", "ADESS", "ADH", "ADJ", "ADJR", "ADJZ", "ADL", "ADM",
        "ADN", "ADR", "ADV", "ADVM", "ADVR", "ADVRS", "ADVRST",
        "ADVS", "ADVZ", "ADVZR", "AEQ", "AF", "AFF", "AFFECT",
        "AFFIRM", "AFFM", "AFFMT", "AFFT", "AFM", "AFOC", "AFW", "AG",
        "AG.N", "AGG", "AGN", "AGNR", "AGR", "AGT", "AJC", "AL",
        "ALIEN", "ALL", "ALLOC", "ALTER", "AM", "AMBIPH", "AMP", "AN",
        "ANA", "ANAPH", "AND", "ANIM", "ANM", "ANP", "ANT", "ANTC",
        "ANTDIR", "ANTE", "ANTEL", "ANTESS", "ANTI", "ANTIC", "ANTIP",
        "ANTLAT", "AO", "AOBL", "AOR", "AP", "APASS", "APF", "APL",
        "APP", "APPL", "APPOS", "APPR", "APPROB", "APR", "APRT",
        "APRX", "APS", "APUD", "AR", "AREA", "ARG", "ART", "AS",
        "ASC", "ASP", "ASRT", "ASS", "ASSC", "ASSERT", "ASSOC",
        "ASSP", "ASST", "ASSU", "ASSUM", "AST", "ASYM", "ATEL",
        "ATN", "ATP", "ATR", "ATT", "ATTEN", "ATTN", "ATTR", "AUD",
        "AUG", "AUX", "AV", "AVERS", "AVERT", "AVOL", "AVR", "B",
        "BCKG", "BEL", "BEN", "BENEF", "BG", "BI", "BOT", "BOU",
        "BOUND", "BR", "BT", "BV", "C", "C.EXIST", "CAP", "CAR",
        "CARD", "CARIT", "CAU", "CAUS", "CC", "CDM", "CDN", "CDP",
        "CE", "CEL", "CELER", "CENT", "CENTRIF", "CENTRIP", "CERT",
        "CESS", "CEXP", "CF", "CFM", "CFOC", "CHEZ", "CHO", "CHR",
        "CIF", "CIR", "CIRC", "CIRCUM", "CIRCUMESS", "CIS", "CISL",
        "CISLOC", "CIT", "CJ", "CJT", "CL", "CLASS", "CLF", "CLFSR",
        "CM", "CMP", "CMPAR", "CMPD", "CMPL", "CMPLT", "CMPR", "CMT",
        "CN", "CNA", "CNCS", "CNCT", "CND", "CNEG", "CNG", "CNGR",
        "CNJ", "CNN", "CNS", "CNSQ", "CNSTR", "CNT", "CNTF", "CNTG",
        "CNTR", "CNTR.FACT", "CNTREXP", "CNTV", "CNV", "CO.AG",
        "CO.REF", "COCAUS", "COH", "COL", "COLL", "COM", "COMIT",
        "COMM", "COMP", "COMPL", "COMPLET", "COMPLR", "COMPR",
        "COMPUL", "COMPV", "CON", "CONC", "CONCESS", "COND", "CONF",
        "CONFIRM", "CONGR", "CONJ", "CONJC", "CONJUN", "CONN", "CONR",
        "CONS", "CONSEC", "CONST", "CONSTR", "CONT", "CONTEMP",
        "CONTIN", "CONTR", "CONV", "COOP", "COORD", "COP", "COR",
        "COREF", "COTEMP", "CP", "CPL", "CQ", "CRAS", "CRD", "CRS",
        "CS", "CSL", "CSM", "CSO", "CST", "CSTVZR", "CT", "CTEMP",
        "CTEXP", "CTG", "CTM", "CTN", "CTR", "CTRFCT", "CU", "CUS",
        "CUST", "CUSTOM", "CV", "CVB", "CV", "D", "DA", "DAT", "DBT",
        "DC", "DCL", "DCSC", "DD", "DE", "DEAG", "DEB", "DEC", "DECL",
        "DED", "DEF", "DEFIN", "DEFOC", "DEFR", "DEI", "DEL",
        "DEL.IMP", "DEM", "DEN", "DENOM", "DEO", "DEOBJ", "DEONT",
        "DEP", "DEPO", "DEPR", "DER", "DEREL", "DERIV", "DES", "DESI",
        "DEST", "DET", "DETR", "DF", "DFLT", "DH", "DIF", "DIM",
        "DIMIN", "DIR", "DIR.EV", "DIREC", "DIREV", "DIS", "DIS.CON",
        "DISB", "DISC", "DISCNT", "DISCONT", "DISJ", "DISSAT", "DIST",
        "DISTR", "DITR", "DIV", "DJ", "DK", "DL", "DLM", "DM", "DN",
        "DNZ", "DO", "DOBJ", "DOM", "DON", "DOWN", "DOX", "DP",
        "DPAST", "DPC", "DPP", "DR", "DRCT", "DS", "DSC", "DSTL",
        "DSTR", "DT", "DTR", "DTRNZ", "DU", "DUB", "DUBIT", "DUMMY",
        "DUPLIC", "DUP", "DUR", "DV", "DV", "DWN", "DY", "DYAD",
        "DYN", "DYNM", "E", "EA", "EC", "EFF", "EFOC", "EGO", "EGR",
        "EH", "EI", "EL", "ELA", "ELAT", "ELPA", "ELV", "EM", "EMO",
        "EMOT", "EMP", "EMPH", "ENC", "END", "ENDO", "EP", "EPENT",
        "EPENTH", "EPI", "EPIS", "EPIST", "EPIT", "EPST", "EQ", "EQL",
        "EQTV", "EQU", "ERG", "ES", "ESS", "EV", "EVD", "EVI", "EVID",
        "EVIT", "EVT", "EX", "EX.BE", "EX.DUR", "EXAL", "EXC", "EXCL",
        "EXCLAM", "EXCLM", "EXEC", "EXESS", "EXFOC", "EXH", "EXH.FOC",
        "EXIS", "EXIST", "EXO", "EXP", "EXP.EV", "EXPECT", "EXPER",
        "EXPL", "EXPR", "EXS", "EXST", "EXT", "EXTRV", "EXTT", "EZ",
        "EZF", "F", "FA", "FAC", "FACT", "FAM", "FAR", "FC", "FCL",
        "FD", "FEM", "FH", "FI", "FILL", "FIN", "FIRSTH", "FMR", "FN",
        "FNL", "FOC", "FORM", "FP", "FPRT", "FPST", "FR",
        "FRACT", "FREQ", "FRM", "FRML", "FRQ", "FRST", "FRT", "FRUS",
        "FRUST", "FRUSTR", "FS", "FT", "FTV", "FUNC", "FUT",
        "FUT.INT", "FV", "G", "G1", "G2", "G3", "G4", "GEM", "GEN",
        "GENER", "GENR", "GENRL", "GENZ", "GER", "GF", "GIV", "GKN",
        "GM", "GN", "GNF", "GNO", "GNOMIC", "GNR", "GNRL", "GNT",
        "GO&", "GPST", "GRD", "GRP", "GT", "GV", "H", "HAB", "HABIT",
        "HBL", "HCR", "HES", "HESIT", "HEST", "HIST", "HML", "HNDR",
        "HNR", "HOD", "HON", "HOR", "HORT", "HPL", "HR.EV", "HRS",
        "HRSY", "HS", "HSY", "HUM", "HYP", "HYPO", "HYPOTH", 
        "IA", "IAM", "IC", "ICM", "ICOM", "ICP", "ICVB", "IDENT",
        "IDENTIF", "IDEO", "IDEOPH", "IDF", "IDPH", "ID", "IE",
        "IFUT", "IGN", "IGNOR", "ILL", "ILLA", "ILLAT", "IM", "IMD",
        "IMI", "IMM", "IMMED", "IMN", "IMP", "IMPARF", "IMPER",
        "IMPERF", "IMPERFV", "IMPERS", "IMPF", "IMPFT", "IMPFV",
        "IMPL", "IMPOSS", "IMPOT", "IMPR", "IMPREC", "IMPRF", "IMPRS",
        "IMPRT", "IMPS", "IMPV", "INAB", "INABL", "INACT",
        "INAL", "INAN", "INANIM", "INC", "INCEP", "INCH", "INCHO",
        "INCIP", "INCL", "INCMP", "INCMPL", "INCOMPL", "INCP",
        "INCPL", "IND", "INDCAUS", "INDEF", "INDEP", "INDET", "INDF",
        "INDH", "INDIC", "INDIR", "INDIV", "INDN", "INDP", "INE",
        "INEL", "INES", "INESS", "INF", "INFER", "INFERN", "INFL",
        "INFR", "ING", "INGR", "INH", "INJ", "INS", "INST", "INSTR",
        "INSV", "INT", "INTEN", "INTENS", "INTENTV", "INTER",
        "INTERESS", "INTERJ", "INTERP", "INTERR", "INTF", "INTJ",
        "INTL", "INTN", "INTNS", "INTR", "INTRJ", "INTRST", "INTRV",
        "INTS", "INTV", "INV", "INVIS", "INVN", "INVOL", "INW", "IO",
        "IOBJ", "IP", "IPAST", "IPD", "IPF", "IPFV", "IPS", "IQ",
        "IR", "IRLS", "IRR", "IRREL", "IRRELEV", "IS", "IT", "ITE",
        "ITER", "ITF", "ITG", "ITIV", "ITM", "ITR", "ITS", "ITV",
        "IVC", "IV", "IZAF", "J", "JUS", "JUSS", "KIN", "KNWN", "KST",
        "L", "L2", "LA", "LAT", "LC", "LCL", "LCV", "LENGTH", "LEX",
        "LF", "LI", "LIG", "LIM", "LINK", "LK", "LKLY", "LL", "LM",
        "LMT", "LN", "LNK", "LOC", "LOG", "LOQ", "LP", "LQ", "LS",
        "LV", "M", "M.E.", "MAL", "MALE", "MAN", "MASC", "MASD",
        "MATUT", "MC", "MD", "MDL", "MDT", "MEA", "MED", "MEDIT",
        "MF", "MID", "MIM", "MIN", "MIR", "MIRN", "MIS", "MIT",
        "MLOC", "MLT", "MNR", "MO", "MOD", "MOM", "MONO", "MOT",
        "MOV", "MP", "MS", "MSAP", "MSD", "MT", "MUL", "MULT", "MVMT",
        "MVR", "N", "N/P", "N1", "NAR", "NARR", "NC", "NCOMPL",
        "NCTM", "NCUR", "NDEF", "NEC", "NEG", "NEGAT", "NEGF", "NEGN",
        "NEUT", "NEUTR", "NEWSIT", "NEX", "NF", "NFC", "NFIN", "NFND",
        "NFPD", "NFUT", "NG", "NH", "NHUM", "NLZ", "NM", "NMASC",
        "NML", "NMLZ", "NMNL", "NMZ", "NOM", "NOMI", "NOMIN", "NOML",
        "NOMN", "NOMS", "NOMZ", "NOMZR", "NONDUM", "NONIN", "NOT",
        "NP", "NPC", "NPDL", "NPF", "NPFV", "NPOSS", "NPP", "NPRS",
        "NPST", "NR", "NS", "NSIT", "NSP", "NT", "NTEL", "NTL", "NTR",
        "NTS", "NUM", "NV", "NVEXP", "NVIS", "NVN", "NVOL", "NVSEN",
        "NW", "NX.PST", "NZ", "NZR", "O", "OB", "OBJ", "OBJV", "OBL",
        "OBLG", "OBLIG", "OBS", "OBV", "OFC", "OINV", "OM", "ONOM",
        "OP", "OPP", "OPT", "OR", "ORD", "ORIG", "OS", "OTHER", "OUT",
        "OV", "P", "P.ANT", "P.IMP", "P.INT", "P/I", "PA", "PABS",
        "PAR", "PART", "PARTIC", "PARTICIP", "PARTVE", "PAS", "PASS",
        "PAST", "PAT", "PAU", "PAUC", "PAUS", "PB", "PC", "PCL",
        "PCP", "PCT", "PDR", "PDS", "PE", "PEG", "PEJ", "PER",
        "PERAMB", "PERF", "PERFORM", "PERFV", "PERI", "PERL", "PERM",
        "PERS", "PERSE", "PERSIS", "PERT", "PERV", "PF", "PFT", "PFV",
        "PHAB", "PHAS", "PI", "PIMPF", "PIMPV", "PINF", "PK", "PL",
        "PLPERF", "PLPF", "PLR", "PLU", "PLUP", "PLUPERF", "PLUPRF",
        "PLUR", "PLURAC", "PM", "PN", "PNC", "PNCL", "PNCT", "PO",
        "PODIR", "POEL", "POESS", "POL", "POS", "POSB", "POSS",
        "POSSB", "POSSD", "POSSIB", "POST", "POSTDIR", "POSTE",
        "POSTEL", "POSTESS", "POSTL", "POSTLAT", "POSTP", "POT",
        "POTEN", "PP", "PPA", "PPAST", "PPERF", "PPF", "PPFV", "PPF",
        "PPL", "PPLE", "PPP", "PPRF", "PPRT", "PPS", "PPT", "PQ",
        "PR", "PRC", "PRE", "PREC", "PRECON", "PRED", "PREDICT",
        "PREP", "PRES", "PRESP", "PRESUPP", "PRET", "PREV", "PREVEN",
        "PRF", "PRFRM", "PRG", "PRH", "PRIOR", "PRIV", "PRL", "PRN",
        "PRO", "PROB", "PROCOMP", "PROD", "PROG", "PROGR", "PROH",
        "PROHIB", "PROL", "PROLAT", "PRON", "PROP", "PROPN", "PROPOS",
        "PROPR", "PROS", "PROSEC", "PROSP", "PROT", "PROV", "PROX",
        "PRP", "PRS", "PRSC", "PRSP", "PRSV", "PRT", "PRTC", "PRTV",
        "PRV", "PRVT", "PRX", "PS", "PSA", "PSR", "PSS", "PSSD",
        "PSSM", "PSSR", "PST", "PST.PR", "PSTN", "PSUP", "PSV", "PT",
        "PTC", "PTCL", "PTCP", "PTCPL", "PTH", "PTL", "PTP", "PTT",
        "PTV", "PU", "PUNC", "PUNCT", "PUR", "PURP", "PV", "PVB",
        "PVP", "PX", "Q", "QM", "QNT", "QP", "QST", "QT", "QU",
        "QUAL", "QUANT", "QUES", "QUEST", "QUO", "QUOT", "QV", "R",
        "R.EXT", "R/A", "R/M", "R/R", "RA", "RAR", "RCP", "RCT",
        "RDP", "RDPL", "RE", "REA", "REAL", "REC", "RECIP", "RECIPR",
        "RECP", "RED", "REDUP", "REF", "REFL", "REFLX", "REG", "REGR",
        "REL", "REL.FUT", "RELEV", "REM", "REP", "REPET", "RES",
        "RESID", "RESP", "REST", "RESU", "RESULT", "RES", "RET",
        "RETRO", "RETURN", "REV", "REVID", "RF", "RFL", "RFLEX",
        "RFLX", "RFR", "RHET", "RL", "RLN", "RLS", "RM", "RMT", "RNR",
        "ROOT", "ROY", "RP", "RPC", "RPI", "RPR", "RPRT", "RPST",
        "RPT", "RPV", "RQ", "RQT", "RR", "RSM", "RSN", "RST", "RSTR",
        "RT", "RT.EXT", "RV", "RX", "S", "S/A", "SA", "SAA", "SAL",
        "SAP", "SB", "SBDIR", "SBEL", "SBEN", "SBESS", "SBJ", "SBJT",
        "SBJV", "SBRD", "SBV", "SCEP", "SD", "SDS", "SE", "SEC",
        "SEJ", "SEM", "SEMBL", "SEMEL", "SEN", "SENS", "SENS.EV",
        "SEP", "SEQ", "SER", "SF", "SFL", "SFN", "SFOC", "SFP", "SFS",
        "SG", "SGLT", "SGT", "SGV", "SH", "SIM", "SIMUL", "SIMV",
        "SING", "SINGL", "SINV", "SIT", "SJ", "SJV", "SKT", "SL",
        "SM", "SMBL", "SMI", "SML", "SMLF", "SMR", "SNS", "SO", "SOC",
        "SP", "SPAT", "SPC", "SPCF", "SPEC", "SPECFC", "SPECFR",
        "SPECL", "SPKR", "SPL", "SPONT", "SPR", "SQ", "SR", "SRC",
        "SRDIR", "SREL", "SRP", "SS", "SSO", "SSS", "ST", "STA",
        "STAT", "STEM", "STIM", "STR", "STT", "STV", "SU", "SUB",
        "SUBDIR", "SUBE", "SUBEL", "SUBJ", "SUBJV", "SUBL", "SUBLAT",
        "SUBORD", "SUBR", "SUBS", "SUBSEC", "SUBST", "SUBV", "SUBZ",
        "SUC", "SUG", "SUP", "SUPDIR", "SUPE", "SUPEL", "SUPER",
        "SUPEREL", "SUPESS", "SUPL", "SUPLAT", "SUPP", "SURP", "SVC",
        "SW", "SYM", "T", "T/A", "TA", "TAG", "TAM", "TAMP", "TB",
        "TEL", "TEM", "TEMP", "TENS", "TENT", "TER", "TERM", "TERMIN",
        "TH", "THEM", "THEMAT", "THM", "TJ", "TKN", "TMA", "TMP",
        "TND", "TNS", "TOD", "TOP", "TOPR", "TOPZ", "TOT", "TP",
        "TPC", "TR", "TRA", "TRAL", "TRANS", "TRANSF", "TRANSL",
        "TRANSLV", "TRANSP", "TRI", "TRIP", "TRL", "TRM", "TRN",
        "TRNS", "TRNSF", "TRNSL", "TRPOSS", "TRZ", "TS", "TV", "TVF",
        "TZ", "U", "UA", "UC", "UF", "UG", "UGR", "UH", "UL",
        "UNCERT", "UND", "UNIF", "UNPOSS", "UNSP", "UNSPEC", "UNW",
        "UP", "UR", "USIT", "UTIL", "UV", "UWPST", "V", "VA", "VAI",
        "VAL", "VB", "VBLZ", "VBLZR", "VBZ", "VBZR", "VCL", "VCO",
        "VE", "VEG", "VEN", "VENT", "VER", "VERB", "VERBL", "VERIF",
        "VERS", "VERT", "VESPERT", "VEVID", "VIA", "VII", "VIRT",
        "VIS", "VLOC", "VLZ", "VN", "VNV", "VOC", "VOL", "VP", "VPL",
        "VR", "VS", "VSM", "VTA", "VTI", "VZ", "WH", "WH.EX", "WH.Q",
        "WHQ", "WIT", "WP", "WPST", "X", "XS", "YNQ", "ZO"]

     self.combine()

   #----------------------------------------------------------------------
   def recognized(self, abbrev):

       return abbrev in self.all

   #----------------------------------------------------------------------
   def combine(self):

       x1 = list(self.beckAndHess.keys())
       x2 = list(self.leipzig.keys())
       x3 = self.wikipedia
       xAll = x1
       xAll.extend(x2)
       xAll.extend(x3)
       xAll = list(set(xAll))
       xAll.sort()
       self.all = xAll

   #----------------------------------------------------------------------
   def getAll(self):

       #x1 = list(self.beckAndHess.keys())
       #x2 = list(self.leipzig.keys())
       #x3 = self.wikipedia
       #xAll = x1
       #xAll.extend(x2)
       #xAll.extend(x3)
       #xAll = list(set(xAll))
       #xAll.sort()

       return self.all

   #----------------------------------------------------------------------
   def lookup(self, abbrev):

       abbrev = abbrev.upper()
       
       if abbrev in self.leipzig.keys():
          return self.leipzig[abbrev]

       if abbrev in self.beckAndHess.keys():
          return self.beckAndHess[abbrev]
      
       return None
   
   #----------------------------------------------------------------------
   
