LANGUAGE = tlingit
EAF = 60MargaretMarsha230618Slexil.eaf
SFMT.FILE = 60MargaretMarsha230618Slexil.yaml
HTML.FILE = 60MargaretMarsha.html
VID=60MargaretMarsha.m4v
TITLE = "Tlingit Conversation \#60"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
