LANGUAGE = tlingit
EAF = 10DavidGeorge230503Slexil.eaf
SFMT.FILE = 10DavidGeorge230503Slexil.yaml
HTML.FILE = 10DavidGeorge.html
VID = DavidGeorge9-9-10.m4v
TITLE = "Tlingit Conversation \#10"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
