EAF = 31RamosChester230715Slexil.eaf
SFMT.FILE = 31RamosChester230715Slexil.yaml
HTML.FILE = 31RamosChester.html
VID=31RamosChester.m4v
TITLE = "Tlingit Conversation \#31"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
