EAF = 67LilyMarge220630Slexil.eaf
SFMT.FILE = 67LilyMarge220630Slexil.yaml
HTML.FILE = 67LilyMarge.html
VID=67LilyMarge.m4v
TITLE = "Tlingit Conversation \#67"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
