EAF = 69SamHans220704Slexil.eaf
SFMT.FILE = 69SamHans220704Slexil.yaml
HTML.FILE = 69SamHans.html
VID=69SamHans.m4v
TITLE = "Tlingit Conversation \#69"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
