LANGUAGE = tlingit
EAF = 26LenaNellie230714Slexil.eaf
SFMT.FILE = 26LenaNellie230714Slexil.yaml
HTML.FILE = 26LenaNellie.html
VID = 26LenaNellie.m4v
TITLE = "Tlingit Conversation \#26"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
