LANGUAGE = tlingit
EAF = 30LenaHans230715Slexil.eaf
SFMT.FILE = 30LenaHans230715Slexil.yaml
HTML.FILE = 30LenaHans.html
VID = 30LenaHans2.m4v
TITLE = "Tlingit Conversation \#30"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/

