default:
	@echo venv
	@echo server
	@echo demo  - record and playback

venv:
	@echo source /Users/paul/github/slexil2/py3105slexil/bin/activate

server:
	python -m http.server 9999 &

demo:
	open http://localhost:9999/recorderPlayerModulesTest.html



