include ../../makefile-shared
LANGUAGE = degXinag
BASE = Canoe241025
EAF =  $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HELP_FILE = ../help-ellen-canoe.html
HTML.FILE = fatherCanoe.html
VID = DXCultHist3pt1Canoe.wav
TITLE = "Sito’ tr’eyh itltsenh My Father made a canoe"
HOST = https://aklanguages.uas.alaska.edu

