include ../../makefile-shared

LANGUAGE = degXinag
BASE =  weWillTry-240402
EAF =  $(BASE).eaf
SFMT.FILE =  $(BASE).yaml
HTML.FILE = weWillTry.html
HELP_FILE = help.html
VID = weWillTry-720.mov
TITLE = "Vitr'enotox - We'll Try"


