include ../../makefile-shared

LANGUAGE = degXinag
BASE =  weWillTry-240402
EAF =  $(BASE).eaf
SFMT.FILE =  $(BASE).yaml
HTML.FILE = weWillTry.html
HELP_FILE = help-weWillTry.html
VID = weWillTry-720.mov
TITLE = "We'll Try"


