EAF = 35Atlin230715Slexil.eaf
SFMT.FILE = 35Atlin230715Slexil.yaml
HTML.FILE = 35Atlin.html
VID=35Atlin1.m4v
TITLE = "Tlingit Conversation \#35"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
