EAF = 43TeslinMen230602Slexil.eaf
SFMT.FILE = 43TeslinMen230602Slexil.yaml
HTML.FILE = 43TeslinMen.html
VID=43TeslinMen.m4v
TITLE = "Tlingit Conversation \#43"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
