EAF = 62MargaretFred230621Slexil.eaf
SFMT.FILE = 62MargaretFred230621Slexil.yaml
HTML.FILE = 62MargaretFred.html
VID=62MargaretFred.m4v
TITLE = "Tlingit Conversation \#62b"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
