EAF = 78SelinaHelenKeriRyker230718Slexil.eaf
SFMT.FILE = 78SelinaHelenKeriRyker230718Slexil.yaml
HTML.FILE = 78SelinaHelenKeriRyker.html
VID=78SelinaHelenKeriRyker.mov
TITLE = "Tlingit Conversation \#78"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
