LANGUAGE = tlingit
EAF = 41TeslinLadies230605Slexil.eaf
SFMT.FILE = 41TeslinLadies230605Slexil.yaml
HTML.FILE = 41TeslinLadies.html
VID=41TeslinLadies.m4v
TITLE = "Tlingit Conversation \#41"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
