EAF = 95LizVernaSelina230802Slexil.eaf
SFMT.FILE = 95LizVernaSelina230802Slexil.yaml
HTML.FILE = 95LizVernaSelina.html
VID = 95LizVernaSelina.mp4
TITLE = "Tlingit Conversation \#95"

include ../makefile-shared
