EAF = 77SelinaHelenKeriRyker230717Slexil.eaf
SFMT.FILE = 77SelinaHelenKeriRyker230717Slexil.yaml
HTML.FILE = 77SelinaHelenKeriRyker.html
VID=77SelinaHelenKeriRyker.mov
TITLE = "Tlingit Conversation \#77"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
