EAF = 44TeslinMen200217AT.eaf
SFMT.FILE = 44TeslinMen200217AT.yaml
HTML.FILE = 44TeslinMen.html
VID=44TeslinMen.m4v
TITLE = "Tlingit Conversation \#44"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
