LANGUAGE = tlingit
EAF = 39Teslin220318AT.eaf
SFMT.FILE = 39Teslin220318AT.yaml
HTML.FILE = 39Teslin.html
VID=39Teslin.m4v
TITLE = "Tlingit Conversation \#39b"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
