LANGUAGE = tlingit
EAF = 38AtlinGrotto230531Slexil.eaf
SFMT.FILE = 38AtlinGrotto230531Slexil.yaml
HTML.FILE = 38AtlinGrotto.html
VID=38AtlinGrotto.m4v
TITLE = "Tlingit Conversation \#38"

include ../makefile-shared
