EAF = 63SelinaMargaret230622Slexil.eaf
SFMT.FILE = 63SelinaMargaret230622Slexil.yaml
HTML.FILE = 63SelinaMargaret.html
VID=63SelinaMargaret.m4v
TITLE = "Tlingit Conversation \#63"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
