EAF = 73AdelineMargaret230708Slexil.eaf
SFMT.FILE = 73AdelineMargaret230708Slexil.yaml
HTML.FILE = 73AdelineMargaret.html
VID=73AdelineMargret.m4v
TITLE = "Tlingit Conversation \#73"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
