include ../../makefile-shared

BASE = PottingClay240821
LANGUAGE = degXinag
EAF =  $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HTML.FILE = clayPots.html
VID = ClayPotsDX4.wav
TITLE = "Etthok Łats - Clay Pots"
HELP_FILE = "help.html"
HOST = https://aklanguages.uas.alaska.edu
