EAF = 57HelenMargaret230608Slexil.eaf
SFMT.FILE = 57HelenMargaret230608Slexil.yaml
HTML.FILE = 57HelenMargaret.html
VID=57HelenMargaret.m4v
TITLE = "Tlingit Conversation \#57"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
