LANGUAGE = tlingit
EAF = 37AtlinSrprizLk230531Slexil.eaf
MEDIA = 37AtlinSrprizLk.mov
SFMT.FILE = 37AtlinSrprizLk230531Slexil.yaml
HTML.FILE = 37AtlinSrprizLk.html
TITLE = "Tlingit Conversation \#37"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
