LANGUAGE = tlingit
EAF = 9IdaCalmegane230503Slexil.eaf
SFMT.FILE = 9IdaCalmegane230503Slexil.yaml
HTML.FILE = 9IdaCalmagne.html
VID = 9IdaCalmagne.m4v
TITLE = "Tlingit Conversation \#9"

include ../makefile-shared
