EAF = 84MargaretMarshaKaneegwal230723Slexil.eaf
SFMT.FILE = 84MargaretMarshaKaneegwal230723Slexil.yaml
HTML.FILE = 84MargaretMarshaKaneegwal.html
VID = 84MargaretMarshaKaneegwal.m4v
TITLE = "Tlingit Conversation \#84"

include ../makefile-shared
