EAF = 85MargaretMarshaKaneegwal220723Slexil.eaf
SFMT.FILE = 85MargaretMarshaKaneegwal220723Slexil.yaml
HTML.FILE = 85MargaretMarshaKaneegwa.html
VID = 85MargaretMarshaKaneegwal.m4v
TITLE = "Tlingit Conversation \#85"

include ../makefile-shared
