EAF = 72AdelineDeborah230706Slexil.eaf
SFMT.FILE = 72AdelineDeborah230706Slexil.yaml
HTML.FILE = 72AdelineDeborah.html
VID=72AdelineDeborah.m4v
TITLE = "Tlingit Conversation \#72"

include ../makefile-shared
