HTML = 6-addVideoPlayer.html

default:
	@echo view
	@echo publish
	@echo viewRemote


publish:
	scp $(HTML) paulshannnon@pshannon.net:public_html/pshannon.net/demos/layout/index.html

viewRemote:
	open https://pshannon.net/demos/layout/

view:
	open $(HTML)
