LANGUAGE = tlingit
EAF = 16WalterJohn230512Slexil.eaf
HTML.FILE = 16WalterJohn.html
SFMT.FILE = 16WalterJohn230512Slexil.yaml
TIER.GUIDE = tierGuide.yaml
VID = WalterJohn.mov
TITLE = "Tlingit Conversation \#16"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
