EAF = 79MargaretDutson230719Slexil.eaf
SFMT.FILE = 79MargaretDutson230719Slexil.yaml
HTML.FILE = 79MargaretDutson.html
VID = 79MargaretDutson.mp4
TITLE = "Tlingit Conversation \#79"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
