LANGUAGE = tlingit
EAF = 42Teslin230606Slexil.eaf
SFMT.FILE = 42Teslin230606Slexil.yaml
HTML.FILE = 42Teslin.html
VID=42Teslin.m4v
TITLE = "Tlingit Conversation \#42"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
