LANGUAGE = tlingit
BASE = 01RuthNora230503Slexil
EAF = $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HTML.FILE = 01RuthNora.html
VID = 1RuthNora2Wide.m4v
TITLE = "Tlingit Conversation \#1"

include ../makefile-shared
