EAF = 61Margaretmarsha230619Slexil.eaf
SFMT.FILE = 61Margaretmarsha230619Slexil.yaml
HTML.FILE = 61MargaretMarsha.html
VID=61MargaretMarsha.m4v
TITLE = "Tlingit Conversation \#61"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
