EAF = 91MabelLiz230729Slexil.eaf
SFMT.FILE = 91MabelLiz230729Slexil.yaml
HTML.FILE = 91MabelLiz.html
VID = 91MabelLiz.mp4
TITLE = "Tlingit Conversation \#91"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
