BASE = 37-38AtlinBerries230715Slexil
EAF = $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HTML.FILE = 37-38AtlinBerries.html
VID=37-38AtlinBerries.m4v
TITLE = "Tlingit Conversation \#37-38"

include ../makefile-shared

