EAF = 80RuthMarshaKianaLance230720Slexil.eaf
SFMT.FILE = 80RuthMarshaKianaLance230720Slexil.yaml
HTML.FILE = 80RuthMarshaKianaLance.html
VID = 80RuthMarshaKianaLance.mov
TITLE = "Tlingit Conversation \#80"

include ../makefile-shared
