EAF = 83aVanSongComposing230505Slexil.eaf
SFMT.FILE = 83aVanSongComposing230505Slexil.yaml
HTML.FILE = 83aVanSong.html
VID = 83VanSongComposing.m4v
TITLE = "Tlingit Conversation \#83"

include ../makefile-shared
