LANGUAGE = tlingit
EAF = 4EthelAnita230503Slexil.eaf
SFMT.FILE = 4EthelAnita230503Slexil.yaml
HTML.FILE = 4EthelAnita.html
VID = 4EthelAnita.m4v
TITLE = "Tlingit Conversation \#4"
include ../makefile-shared

HOST = https://aklanguages.uas.alaska.edu/
