EAF = 89GeorgeMargaret230726Slexil.eaf
SFMT.FILE = 89GeorgeMargaret230726Slexil.yaml
HTML.FILE = 89GeorgeMargaret.html
VID = 89GeorgeMargaret.m4v
TITLE = "Tlingit Conversation \#89"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/

