LANGUAGE = tlingit
EAF = 23IreneLillian230714Slexil.eaf
SFMT.FILE = 23IreneLillian230714Slexil.yaml
VID = 23IreneLillianIshmael.mp4
HTML.FILE = 23IreneLillian.html
TITLE = "Tlingit Conversation \#23"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
