EAF = 33GeorgeLena230715Slexil.eaf
SFMT.FILE = 33GeorgeLena230715Slexil.yaml
HTML.FILE = 33GeorgeLena.html
VID=33GeorgeLena.m4v
TITLE = "Tlingit Conversation \#33"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/

