EAF = 88GeorgeMargaret230725Slexil.eaf
SFMT.FILE = 88GeorgeMargaret230725Slexil.yaml
HTML.FILE = 88GeorgeMargaret.html
VID = 88GeorgeMargaret.m4v
TITLE = "Tlingit Conversation \#88"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
