LANGUAGE = tlingit
EAF = 39Atlin230601Slexil.eaf
SFMT.FILE = 39Atlin230601Slexil.yaml
HTML.FILE = 39Atlin.html
VID=39Atlin.m4v
TITLE = "Tlingit Conversation \#39"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
