LANGUAGE = tlingit
EAF = 28LorraineVincent230715Slexil.eaf
SFMT.FILE = 28LorraineVincent230715Slexil.yaml
HTML.FILE = 28LorraineVincent.html
VID = 28LorraineVincent2.m4v
TITLE = "Tlingit Conversation \#28"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
