LANGUAGE = tlingit
EAF = 45Carcross240327Slexil.eaf
SFMT.FILE = 45Carcross240327Slexil.yaml
HTML.FILE = 45carcross.html
VID = 45Carcross.m4v
TITLE = "Tlingit Conversation \#45"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
