LANGUAGE = tlingit
EAF = 49Carcross230504Slexil.eaf
SFMT.FILE = 49Carcross230504Slexil.yaml
HTML.FILE = 49Carcross.html
VID=49Carcross.m4v
TITLE = "Tlingit Conversation \#49"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/

