LANGUAGE = tlingit
EAF = 29LenaHans230715Slexil.eaf
HTML.FILE = 29LenaHans.html
VID = 29LenaHans.m4v
SFMT.FILE = 29LenaHans230715Slexil.yaml
TITLE = "Tlingit Conversation \#29"

include ../makefile-shared
