LANGUAGE = tlingit
BASE.NAME = 47Carcross
EAF = $(BASE.NAME).eaf
HTML.FILE = $(BASE.NAME).html
SFMT.FILE = $(BASE.NAME).yaml
VID = 47Carcross.m4v
TITLE = "Tlingit Conversation \#47"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/

