LANGUAGE = tlingit
EAF = 54SoboleffRamos230606Slexil.eaf
SFMT.FILE = 54SoboleffRamos230606Slexil.yaml
HTML.FILE = 54SoboleffRamos.html
VID = 54SoboleffRamos.m4v
TITLE = "Tlingit Conversation \#54"

include ../makefile-shared
