LANGUAGE = tlingit
EAF = 59Lena230614Slexil.eaf
SFMT.FILE = 59Lena230614Slexil.yaml
HTML.FILE = 59Lena.html
VID=59LenaJuly30.m4v
TITLE = "Tlingit Conversation \#59"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
