LANGUAGE = tlingit
EAF = 12HelenFloBaby220823AT.eaf
VID = 12HelenFloBaby8-7-10.m4v
HTML.FILE = 12HelenFloBaby.html
SFMT.FILE = 12HelenFloBaby220823AT.yaml
TIER.GUIDE = tierGuide.yaml
TITLE = "Tlingit Conversation \#12"

include ../makefile-shared
