# degXinag/howIWentWithMyHusband-part1/makefile
include ../../makefile-shared
LANGUAGE = degXinag
BASE = DXCultHist1Husband1
EAF = $(BASE).eaf
SFMT.FILE = $(BASE).yaml
HTML.FILE = husband-part-1.html
VID = DXCultHist1.2Husb.wav
TITLE = "How I Went with my Husband - Part 1"
HELP_FILE = "help.html"
HOST = https://aklanguages.uas.alaska.edu
