include ../../makefile-shared

LANGUAGE = lushootseed
BASE =  starChild-susieSampsonPeter
SFMT.FILE =  $(BASE).yaml
HTML.FILE = $(BASE).html
HELP_FILE = help.html
VID = wauem_2005001-hilbert_0976_side2.wav
TITLE = "Star Child - Susie Sampson Peter"


