LANGUAGE = tlingit
EAF = 24LenaNellie2230714Slexil.eaf
SFMT.FILE = 24LenaNellie2230714Slexil.yaml
HTML.FILE = 24LenaNellie.html
VID = LenaNellie24.m4v
TITLE = "Tlingit Conversation \#24"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
