EAF = 87GeorgeMargaret230724Slexil.eaf
SFMT.FILE = 87GeorgeMargaret230724Slexil.yaml
HTML.FILE = 87GeorgeMargaret.html
VID = 87GeorgeMargaret.m4v
TITLE = "Tlingit Conversation \#87"

include ../makefile-shared
