EAF = 90MargaretMarsha230727Slexil.eaf
SFMT.FILE = 90MargaretMarsha230727Slexil.yaml
HTML.FILE = 90MargaretMarsha.html
VID = 90MargaretMarsha.m4v
TITLE = "Tlingit Conversation \#90"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
