LANGUAGE = tlingit
EAF = 13-14MargaretMarsha230503Slexil.eaf
VID = 13-14MargaretMarsha.m4v
HTML.FILE = 13-14MargaretMarsha.html
SFMT.FILE = 13-14MargaretMarsha230503Slexil.yaml
TIER.GUIDE = tierGuide.yaml
TITLE = "Tlingit Conversation \#13-14"


include ../makefile-shared
