EAF = 75JennieAdeline220712Slexil.eaf
SFMT.FILE = 75JennieAdeline220712Slexil.yaml
HTML.FILE = 75JennieAdeline.html
VID=75JennieAdeline.m4v
TITLE = "Tlingit Conversation \#75"

include ../makefile-shared
