LANGUAGE = tlingit
EAF = 20NoraFred230714Slexil.eaf
HTML.FILE = 20NoraFred.html
SFMT.FILE = 20NoraFred230714Slexil.yaml
TIER.GUIDE = tierGuide.yaml
VID = 
TITLE = "Tlingit Conversation \#20"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
