EAF = 48Carcross230426Slexil.eaf
SFMT.FILE = 48Carcross230426Slexil.yaml
HTML.FILE = 48Carcross.html
VID=48Carcross.m4v
TITLE = "Tlingit Conversation \#48"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
