EAF = 94FrankSelina230113Slexil.eaf
SFMT.FILE = 94FrankSelina230113Slexil.yaml
HTML.FILE = 94FrankSelina.html
VID = 94FrankSelina.mp4
TITLE = "Tlingit Conversation \#94"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
