LANGUAGE = tlingit
EAF = 5ArchieGeorge230714Slexil.eaf
SFMT.FILE = 5ArchieGeorge230714Slexil.yaml
HTML.FILE = 5ArchieGeorge.html
VID = ArchieGeorge5-2.mov
TITLE = "Tlingit Conversation \#5"

include ../makefile-shared
