LANGUAGE = tlingit
EAF = 58G̱unaakw230609Slexil.eaf
SFMT.FILE = 58G̱unaakw230609Slexil.yaml
HTML.FILE = 58Gunaakw.html
VID=58G̱unaakw1008.m4v
TITLE = "Tlingit Conversation \#58"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
