EAF = 64SelinaMargaret230623Slexil.eaf
SFMT.FILE = 64SelinaMargaret230623Slexil.yaml
HTML.FILE = 64SelinaMargaret.html
VID=64SelinaMargaret.m4v
TITLE = "Tlingit Conversation \#64"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
