LANGUAGE = tlingit
EAF = 82BillFred230722Slexil.eaf
SFMT.FILE = 82BillFred230722Slexil.yaml
HTML.FILE = 82BillFred.html
VID = 82BillFred.m4v
TITLE = "Tlingit Conversation \#82"

include ../makefile-shared
HOST = https://aklanguages.uas.alaska.edu/
